REGISTRATION_EMAIL = "REGISTRATION_EMAIL" #V
NEW_COVID_TO_RESTAURANT_BOOKING = "NEW_COVID_TO_RESTAURANT_BOOKING" #V
NEW_POSITIVE_WAS_IN_RESTAURANT = "NEW_POSITIVE_WAS_IN_RESTAURANT" #V
EMAIL_TO_FRIEND = "EMAIL_TO_FRIEND" #V
CONFIRMATION_BOOKING = "CONFIRMATION_BOOKING" #V

