version: "3.8"

services:
    sendemail:
        depends_on:
            - redis
        restart: always
        build: .
        ports:
            - "5001:5001"
        expose:
            - "5001"
    celery:
        depends_on:
            - redis
            - sendemail
        build: .
        restart: always
        command: celery -A background.celery_app worker --loglevel=DEBUG
        links:
            -  redis
    redis:
        image: "redis:alpine"
        container_name: rd02
        expose:
            - "6379"