name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send Email microservices testing
        run: |
          docker-compose up -d
          docker-compose exec -T sendemail pytest --cov-config .coveragerc --cov . --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true